import Link from "next/link";
import { notFound } from "next/navigation";
import { manualEventCheckIn, reverseEventCheckIn } from "@/app/admin/check-in/actions";
import { AdminShell } from "@/components/admin-shell";
import { EventCheckInScanner } from "@/components/event-check-in-scanner";
import { requireEventCheckInAccess } from "@/lib/admin/auth";
import { formatTaipeiDateTime } from "@/lib/admin/labels";
import { ticketTokenSuffix } from "@/lib/events/ticket";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
export default async function EventCheckInPage({ params, searchParams }: { params: Promise<{ eventId: string }>; searchParams: Promise<{ q?: string }> }) { const [{ eventId }, query] = await Promise.all([params, searchParams]); const session = await requireEventCheckInAccess(eventId); const q = query.q?.trim() || ""; const event = await prisma.inPersonEvent.findUnique({ where: { id: eventId }, include: { registrations: { where: { status: "CONFIRMED", OR: q ? [{ name: { contains: q, mode: "insensitive" } }, { registrationNo: { contains: q, mode: "insensitive" } }, { email: { contains: q, mode: "insensitive" } }, { phone: { endsWith: q } }] : undefined }, orderBy: { name: "asc" }, include: { checkIn: true } } } }); if (!event) notFound(); const checked = event.registrations.filter((item) => item.checkIn && !item.checkIn.reversedAt).length; return <AdminShell adminName={session.adminUser.name} adminRole={session.adminUser.role}><div className="admin-page-heading"><div><Link className="admin-breadcrumb" href="/admin/check-in">← 選擇其他活動</Link><h1>{event.title}</h1><span>{event.venueName}・已報到 {checked}／{event.registrations.length}</span></div></div><EventCheckInScanner eventId={eventId} /><section className="admin-panel"><div className="admin-panel-heading"><h2>人工搜尋報到</h2><form className="admin-filter-bar checkin-search"><input name="q" defaultValue={q} placeholder="姓名、編號、Email 或電話末碼" /><button type="submit">搜尋</button></form></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>參加人</th><th>報名編號</th><th>票券末碼</th><th>狀態</th><th>操作</th></tr></thead><tbody>{event.registrations.map((item) => { const active = item.checkIn && !item.checkIn.reversedAt; return <tr key={item.id}><td><strong>{item.name}</strong><small>{item.phone.slice(-4)}・{item.email}</small></td><td>{item.registrationNo}</td><td>{ticketTokenSuffix(item.ticketTokenHash)}</td><td>{active ? `已報到 ${formatTaipeiDateTime(item.checkIn!.checkedInAt)}` : "未報到"}</td><td>{active ? <form action={reverseEventCheckIn}><input type="hidden" name="eventId" value={eventId} /><input type="hidden" name="registrationId" value={item.id} /><input type="hidden" name="note" value="現場人員撤銷誤報到" /><button type="submit">撤銷報到</button></form> : <form action={manualEventCheckIn}><input type="hidden" name="eventId" value={eventId} /><input type="hidden" name="registrationId" value={item.id} /><button type="submit">確認報到</button></form>}</td></tr>; })}{!event.registrations.length ? <tr><td colSpan={5}>沒有符合條件的正取名單。</td></tr> : null}</tbody></table></div></section></AdminShell>; }
