-- 排程通知類型與冪等識別碼。
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'MEMBERSHIP_EXPIRING';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'MEMBER_PRIORITY_OPEN';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'LIVE_REMINDER';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'REPLAY_CLOSING';
ALTER TYPE "EmailStatus" ADD VALUE IF NOT EXISTS 'PROCESSING';

ALTER TABLE "EmailLog"
  ADD COLUMN "dedupeKey" TEXT,
  ADD COLUMN "metadata" JSONB;

CREATE UNIQUE INDEX "EmailLog_dedupeKey_key" ON "EmailLog"("dedupeKey");
